; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-atom]
platform = https://github.com/platformio/platform-espressif32.git
board = m5stack-atom
framework = arduino
extra_scripts = build_web.py
lib_deps = 
	ESP32Async/ESPAsyncWebServer
	bblanchon/ArduinoJson
	fastled/FastLED@^3.10.3
